// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "bf3a8d31-66ee-4cd7-ab63-6c466d9e2fe6");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1650498898);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1650498920);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1650572926);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1650572951);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1650498924);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8274253c-b1af-4e58-985a-f3356678c3ec}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1650498878);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f73e3977-f4aa-474b-8340-2a25097fad32}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1650572950534");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1650574730534");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1650572952145");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1650594552145");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220202182137");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1650572937");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220202182137");
user_pref("browser.startup.homepage_override.mstone", "97.0");
user_pref("browser.startup.lastColdStartupCheck", 1650572929);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1650498901676");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "97.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "da841f91ea3645baa393ce4b353a257e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1650572931);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220202182137");
user_pref("extensions.lastAppVersion", "97.0");
user_pref("extensions.lastPlatformVersion", "97.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e4131f84-9ac9-48e5-8045-a50c44ec0275\",\"formautofill@mozilla.org\":\"a4e0062b-e532-4bb4-b918-2b29ad7ba855\",\"pictureinpicture@mozilla.org\":\"93e1be51-faf7-4582-8c41-dec45c382680\",\"screenshots@mozilla.org\":\"d9b420f1-8b79-4149-b698-e001da029644\",\"webcompat-reporter@mozilla.org\":\"08d28a8b-9ed5-42aa-9d5c-cbcbd3f1f7aa\",\"webcompat@mozilla.org\":\"cd552255-0c5a-4584-9c36-770116a2d099\",\"default-theme@mozilla.org\":\"81212204-9b15-42db-bcf5-127863e955fd\",\"addons-search-detection@mozilla.com\":\"2e2e178f-69d6-47c4-93b3-1080bef4688d\",\"google@search.mozilla.org\":\"813474a1-4510-4ab3-a079-62d3bb1b8f1c\",\"amazondotcom@search.mozilla.org\":\"25ba3198-326b-4b64-b94d-9e4d4f8c67ce\",\"drae@search.mozilla.org\":\"7a593c54-975e-47da-a27c-30f50895255b\",\"wikipedia@search.mozilla.org\":\"275621da-5719-4c9b-99ec-3b01ede18014\",\"ddg@search.mozilla.org\":\"10bff1e8-f916-4411-adff-f8d1a6722af8\",\"mercadolibre@search.mozilla.org\":\"c581c757-ed06-486f-a258-948512bb63f4\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1650498916);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "9b541a39-9e99-4406-8c48-03db16257aff");
user_pref("toolkit.startup.last_success", 1650572913);
user_pref("toolkit.telemetry.cachedClientID", "c62a4711-9def-416c-a941-7774427e8884");
user_pref("toolkit.telemetry.previousBuildID", "20220202182137");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
